name: transfran
description: aplication for freelance

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_countdown_timer: ^1.1.0
  flutter_spinning_wheel: ^1.1.0
  adobe_xd: ^1.0.0+1
  flutter_open_whatsapp: ^0.1.2


  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_launcher_name: "^0.0.1"

  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
  - images/logo100.png
  - images/logo_lo.png
  - images/rouletteesp.png
  - images/selectle/fondo.png
  - images/selectle/logo.png
  - images/service/adventure.png
  - images/service/beer.png
  - images/service/bus.png
  - images/service/eco.png
  - images/service/englishmen.png
  - images/service/esservice.png
  - images/service/taxi.png
  - images/service/vino.png
  - images/service/fondo2.png
  - images/transport/crafter.png
  - images/transport/entrans.png
  - images/transport/estransport.png
  - images/transport/sedan.png
  - images/transport/suburban.png
  - images/transport/toyota.png
  - images/transport/transporter.png
  - images/roulette/instico.png
  - images/roulette/palo.png
  - images/roulette/pointer.png
  - images/roulette/rouletteeng.png
  - images/roulette/rouletteesp.png
  - images/roulette/friends.png
  - images/roulette/facico.png
  - images/roulette/engmen.png
  - images/roulette/esmen.png
  - images/moreserv/esmen.png
  - images/moreserv/engmen.png
  - images/moreserv/bike.png
  - images/moreserv/climb.png
  - images/moreserv/heli.png
  - images/moreserv/zip.png
  - images/cost/came1.png
  - images/cost/came2.png
  - images/cost/came3.png
  - images/final/finalen.png
  - images/final/finalesp.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
